spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=America/Bogota
        username: root
        password: 6991
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
